decentraland/account

package-lock.json
package.json
tsconfig.json
tslint.json

chore: tslint configuration as marketplace repo

---

src/components/AccountCard/AccountCard.css
src/components/AccountCard/AccountCard.tsx
src/components/AccountCard/AccountCard.types.tsx
src/components/AccountCard/AccountCardContainer.css
src/components/AccountCard/AccountCardContainer.tsx
src/components/AccountCard/AccountCardContainer.types.tsx
src/components/AccountCard/index.ts
src/components/AccountHeader/AccountHeader.css
src/components/AccountHeader/AccountHeader.tsx
src/components/AccountHeader/AccountHeader.types.tsx
src/components/AccountHeader/index.ts
src/components/HomePage/HomePage.css
src/components/HomePage/HomePage.tsx
src/index.css
src/locales/en.json
src/locales/es.json
src/locales/zh.json
src/themes/index.ts

This is just a primer mockup for Header / Cards interface based in https://www.figma.com/file/t7YG4aH1T0EfwI53dPfCuH/Account?node-id=94%3A24

Feat: Mockup for Account Cards / Header

---

src/components/AccountHeader/AccountHeader.container.ts
src/components/HomePage/AccountHeader/AccountHeader.tsx
src/components/HomePage/AccountHeader/AccountHeader.types.tsx
src/components/HomePage/AccountHeader/index.ts
src/components/HomePage/HomePage.tsx
src/components/Navbar/Navbar.container.ts
src/components/Navbar/Navbar.css
src/components/Navbar/Navbar.tsx
src/components/Navbar/Navbar.types.ts
src/components/Navbar/index.ts
src/components/UserMenu/UserMenu.container.ts
src/components/UserMenu/UserMenu.css
src/components/UserMenu/UserMenu.tsx
src/components/UserMenu/UserMenu.types.ts
src/components/UserMenu/index.ts
src/locales/en.json
src/locales/es.json
src/locales/zh.json
src/modules/locations.ts

Added `UserMenu` to navbar and connected header to profile in state

feat: added UserMenu

---

src/components/HomePage/AccountCard/AccountCard.css
src/components/HomePage/AccountCard/AccountCard.tsx
src/components/HomePage/AccountCard/AccountTransactions/AccountTransaction/AccountTransaction.container.tsx
src/components/HomePage/AccountCard/AccountTransactions/AccountTransaction/AccountTransaction.tsx
src/components/HomePage/AccountCard/AccountTransactions/AccountTransaction/AccountTransaction.types.tsx
src/components/HomePage/AccountCard/AccountTransactions/AccountTransaction/index.ts
src/components/Modals/TransactionDetailModal/TransactionDetailModal.css
src/components/Modals/TransactionDetailModal/TransactionDetailModal.tsx
src/components/Modals/TransactionDetailModal/index.ts
src/components/Modals/index.ts
src/locales/en.json
src/locales/es.json
src/locales/zh.json

Feat: transaction detail modal

Feat: transaction detail modal

---

src/components/HomePage/AccountCard/AccountCard.container.ts
src/components/HomePage/AccountCard/AccountCard.css
src/components/HomePage/AccountCard/AccountCard.tsx
src/components/HomePage/AccountCard/AccountCard.types.tsx
src/components/HomePage/AccountCard/AccountTransactions/AccountTransaction/AccountTransaction.css
src/components/HomePage/AccountCard/AccountTransactions/AccountTransaction/AccountTransaction.tsx
src/components/HomePage/AccountHeader/AccountHeader.container.ts
src/components/HomePage/AccountHeader/index.ts
src/components/HomePage/HomePage.css
src/components/HomePage/HomePage.tsx
src/components/Modals/SeeAllTransactionModal/SeeAllTransactionModal.css
src/components/Modals/SeeAllTransactionModal/SeeAllTransactionModal.tsx
src/components/Modals/SeeAllTransactionModal/index.ts
src/components/Modals/index.ts
src/locales/en.json
src/locales/es.json
src/locales/zh.json
src/modules/profile/selectors.ts
tslint.json

Feat: See all transactions Modal

Feat: See all transactions Modal

---

package-lock.json
package.json
src/components/Routes/Routes.tsx
src/components/SignInPage/SignInPage.css
src/components/SignInPage/SignInPage.tsx
src/components/SignInPage/index.ts
src/modules/location/sagas.ts
src/modules/sagas.ts

Feat: Sign In page

---

.ci/.env.dev
.ci/.env.prd
.ci/.env.stg
.env.example
src/components/HomePage/AccountHeader/AccountHeader.tsx
vercel.json

Feat: links for header buttons. Change Alias & Edit Avatar

Feat: links for header buttons. Change Alias & Edit Avatar

---

src/components/Routes/Routes.container.tsx
src/components/Routes/Routes.tsx
src/components/Routes/Routes.types.ts
src/components/Routes/index.ts

Feat: Adding SignIn Page redirection when the user is not logged in

Feat: Adding SignIn Page redirection

---

src/components/HomePage/AccountCard/AccountTransactions/AccountTransactions.css
src/components/HomePage/AccountCard/AccountTransactions/AccountTransactions.tsx
src/components/HomePage/AccountCardContainer/AccountCardContainer.css
src/locales/en.json
src/locales/es.json
src/locales/zh.json

fix: flex height on container of Transactions

fix: flex height on container of Transactions

---

public/index.html
src/index.tsx
src/modules/analytics/track.ts

feat: track events

---

src/components/Modals/ConvertManaModal/ConvertManaModal.container.tsx
src/components/Modals/ConvertManaModal/ConvertManaModal.css
src/components/Modals/ConvertManaModal/ConvertManaModal.tsx
src/components/Modals/ConvertManaModal/ConvertManaModal.types.ts
src/components/Modals/TransferManaModal/TransferManaModal.container.tsx
src/components/Modals/TransferManaModal/TransferManaModal.css
src/components/Modals/TransferManaModal/TransferManaModal.tsx
src/components/Modals/TransferManaModal/TransferManaModal.types.ts
src/locales/en.json
src/locales/es.json
src/locales/zh.json

Feat: disable not enough balance && Max button to fill mana amount
This close #99 and #100

Feat: disable not enough balance && Max button to fill mana amount

---

src/components/Modals/ConvertManaModal/ConvertManaModal.css
src/components/Modals/ConvertManaModal/ConvertManaModal.tsx
src/components/Modals/TransferManaModal/TransferManaModal.css
src/components/Modals/TransferManaModal/TransferManaModal.tsx
src/locales/en.json
src/locales/es.json
src/locales/zh.json

Feat: Adding fees warning legend.
This close #103

Feat: Adding fees warning legend

---

.github/workflows/node.yml
package-lock.json

This PR adds a CI pipeline to install, build and test the account package.

chore: Add CI pipeline

---

package-lock.json
package.json

This is to fully support wallet connect

feat: upgrade dapps to latest version

---

src/modules/migrations/v2.ts

Closes #151 
Fix migration to consider the case in the issue.
Might be better to solve it directly in @decentraland/dapps

fix: First time usage migration issue

---

package-lock.json
package.json

bump `decentraland-dapps` to latest version

feat: bump dapps

---

package-lock.json
package.json
public/index.html
src/setupTests.ts

This PR uses segment from the analytics module.

feat: Use segment from the analytics module

---

src/components/HomePage/AccountHeader/AccountHeader.tsx
src/locales/en.json
src/locales/es.json
src/locales/zh.json

feat: Add "Get a name" button if the user has no name associated

---

package-lock.json
package.json

Suggested fix for "Invalid Remainder" error.
https://github.com/maticnetwork/matic.js/discussions/319#discussioncomment-2179505

chore: Bump maticjs version

---

package-lock.json
package.json

chore: bump dcl-dapps

---

package-lock.json
package.json

This update includes automatic tracking of the wallet connection

chore(trackConnectWallet): Update dapps lib to track connect

---

src/config/env/dev.json
src/config/env/prod.json
src/config/env/stg.json

chore: use cloudflare proxies

---

package-lock.json
package.json

Related to https://github.com/decentraland/decentraland-dapps/pull/335

chore: Upgrade dapps

---

package-lock.json
package.json

Fixes issue were profile deployments were breaking

feat: Update dapps

---

package-lock.json
package.json
src/components/Modals/index.ts
src/modules/modal/sagas.ts

This PR upgrades the decentraland-ui and decentraland-dapps packages

chore: Upgrade decentraland-ui and decentraland-dapps packages

---

.github/workflows/set-rollout-manual.yaml

This PR updates the ubuntu version in set-rollout-manual action

chore: Update ubuntu version in set-rollout-manual action

---

package-lock.json
package.json
src/locales/en.json
src/locales/es.json
src/locales/zh.json
src/modules/analytics/track.ts
src/modules/mana/selectors.ts
src/modules/mana/utils.ts

Related to https://github.com/decentraland/decentraland-dapps/pull/434

feat: Track Refunded purchases

---

package-lock.json
package.json

Bump decentraland dapps version to include https://github.com/decentraland/decentraland-dapps/pull/443

feat: bump decentraland dapps version

---

.github/workflows/build-release.yaml

feat: Create releases and upload sourcemaps

---

src/locales/es.json
src/locales/zh.json

Closes https://github.com/decentraland/catalyst/issues/1750
Closes https://github.com/decentraland/catalyst/issues/1751
Closes https://github.com/decentraland/catalyst/issues/1752

fix: Translation issues

---

.github/workflows/audit.yml
.github/workflows/build-release.yaml
.github/workflows/test.yaml
package-lock.json
package.json

This PR updates the build process to use node 20.

fix: Use node 20

---

src/components/HomePage/AccountCard/AccountCard.css
src/index.tsx

feat: change to dark mode

---

src/components/MainPage/MainPage.container.ts
src/components/MainPage/MainPage.styled.ts
src/components/MainPage/MainPage.tsx
src/components/MainPage/MainPage.types.tsx
src/components/Notifications/NotificationEmailCard/NotificationEmailCard.styled.ts
src/components/Notifications/NotificationGroupCard/NotificationGroupCard.container.ts
src/components/Notifications/NotificationGroupCard/NotificationGroupCard.spec.tsx
src/components/Notifications/NotificationGroupCard/NotificationGroupCard.styled.ts
src/components/Notifications/NotificationGroupCard/NotificationGroupCard.tsx
src/components/Notifications/NotificationGroupCard/NotificationGroupCard.types.ts
src/components/Notifications/Notifications.tsx
src/modules/subscription/sagas.ts

feat: show one accordion at a time
feat: redirect to root after code validation failed
style: UI

feat: move error message to main page

---

package-lock.json
package.json
src/components/Routes/Routes.tsx

feat: move page tracking to hook

---

src/components/Navbar/Navbar.container.ts
src/components/Navbar/Navbar.tsx
src/components/Navbar/Navbar.types.ts
src/modules/location/sagas.spec.ts
src/modules/location/sagas.ts
src/modules/store.ts
src/modules/subscription/sagas.spec.ts
src/modules/subscription/sagas.ts

Remove connected react router in sagas

feat: remove connected react router from sagas

---

package-lock.json
package.json
src/components/Routes/Routes.container.tsx
src/components/Routes/Routes.tsx
src/components/Routes/Routes.types.ts
src/index.tsx
src/modules/modal/sagas.ts
src/modules/reducer.ts
src/modules/sagas.ts
src/modules/store.ts
src/specs/store.ts
src/specs/utils.tsx

Remove `connected-react-router` library from dapp

feat: remove connected react router

---

jest.config.ts
package-lock.json
package.json
src/components/Routes/Routes.tsx

This PR updates the intercom component used to a new one with data augmented to have a better knowledge of the users reporting an error, improving the support team flow

feat: Update intercom component

---

package-lock.json
package.json
src/components/Notifications/NotificationGroupCard/NotificationGroupCard.container.ts
src/components/Notifications/NotificationGroupCard/NotificationGroupCard.tsx
src/components/Notifications/NotificationGroupCard/NotificationGroupCard.types.ts
src/components/Notifications/Notifications.container.ts
src/components/Notifications/Notifications.tsx
src/components/Notifications/Notifications.types.ts
src/locales/en.json
src/locales/es.json
src/locales/zh.json
src/modules/features/selectors.ts
src/modules/features/types.ts
src/modules/sagas.ts
src/modules/subscription/types.ts
src/modules/subscription/utils.ts

This PR adds a new section to Email Notifications regarding Marketplace Credits.

feat: opt-in/out and subscriptions for Credits emails

---

src/components/CreditsEmail/CreditsEmail.tsx
src/components/Notifications/Notifications.tsx
src/images/icons/dcl.svg

This PR:
- Solves the rendering of the DCL icon at the Credits Email Confirmation page
- Sort the Email Notifications section to have Marketplace Credits below Marketplace

fix: credits-integration
